In [1]:
import pandas as pd

In [2]:
# Load the Excel file into a DataFrame
file_path = "..\dataset\Online Retail.xlsx"   

df = pd.read_excel(file_path)

# Check the first few rows
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
# Basic dataset overview
df.shape

(541909, 8)

In [5]:
# Column names and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [7]:
# Descriptive statistics for numerical columns
numeric_cols = ["Quantity", "UnitPrice"]

df[numeric_cols].describe()

            Quantity      UnitPrice
count  541909.000000  541909.000000
mean        9.552250       4.611114
std       218.081158      96.759853
min    -80995.000000  -11062.060000
25%         1.000000       1.250000
50%         3.000000       2.080000
75%        10.000000       4.130000
max     80995.000000   38970.000000

In above statistics we can see that in the Quantity column we have negative values present. That shouldn't be the case as that column description says "the quantities of each product (item) per transaction".
Same is the case with Unit Price column. Need to identify this thing and tackle it smartly.

In [8]:
# Mode values for categorical columns
categorical_cols = ["StockCode", "CustomerID", "Country"]

df[categorical_cols].mode()

  StockCode  CustomerID         Country
0    85123A     17841.0  United Kingdom

From above statistics we can understand which values appeared maximum time in the data. Through this we know that which StockCode is getting sold the most, which customer is ordering the maximum stock and which country is buying the most stock.

In [9]:
# Negative Quantity (likely returns)
neg_quantity_df = df[df["Quantity"] < 0]

# Negative UnitPrice (less common, might be data issues)
neg_price_df = df[df["UnitPrice"] < 0]

In [10]:
neg_quantity_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom

In [11]:
neg_price_df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [12]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [5]:
# Calculate percentage of null values in specific columns

null_percentage = (
    df[["CustomerID", "Description"]]
    .isnull()
    .mean() * 100
)

# print(null_percentage)

# Create a summary table for null values

null_summary = pd.DataFrame({
    "Null Count": df[["CustomerID", "Description"]].isnull().sum(),
    "Null Percentage": (df[["CustomerID", "Description"]].isnull().mean() * 100)
})

null_summary

             Null Count  Null Percentage
CustomerID       135080        24.926694
Description        1454         0.268311

In [13]:
# Rows where CustomerID is null

customerid_null_df = df[df["CustomerID"].isnull()]

In [14]:
display(customerid_null_df)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1447,536544,21790,VINTAGE SNAP CARDS,9,2010-12-01 14:32:00,1.66,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
541536,581498,85099B,JUMBO BAG RED RETROSPOT,5,2011-12-09 10:26:00,4.13,NaN,United Kingdom
541537,581498,85099C,JUMBO BAG BAROQUE BLACK WHITE,4,2011-12-09 10:26:00,4.13,NaN,United Kingdom
541538,581498,85150,LADIES & GENTLEMEN METAL SIGN,1,2011-12-09 10:26:00,4.96,NaN,United Kingdom
541539,581498,85174,S/4 CACTI CANDLES,1,2011-12-09 10:26:00,10.79,NaN,United Kingdom
541540,581498,DOT,DOTCOM POSTAGE,1,2011-12-09 10:26:00,1714.17,NaN,United Kingdom

In [10]:
# Rows where both CustomerID and Description are null

null_customer_description_df = df[
    (df["CustomerID"].isnull()) & 
    (df["Description"].isnull())
]

display(null_customer_description_df)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
535322,581199,84581,NaN,-2,2011-12-07 18:26:00,0.0,NaN,United Kingdom
535326,581203,23406,NaN,15,2011-12-07 18:31:00,0.0,NaN,United Kingdom
535332,581209,21620,NaN,6,2011-12-07 18:35:00,0.0,NaN,United Kingdom
536981,581234,72817,NaN,27,2011-12-08 10:33:00,0.0,NaN,United Kingdom
538554,581408,85175,NaN,20,2011-12-08 14:06:00,0.0,NaN,United Kingdom

In [3]:
# Remove rows where BOTH CustomerID and Description are null

df = df[
    ~(
        (df["CustomerID"].isnull()) & 
        (df["Description"].isnull())
    )
]

In [4]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     133626
Country             0
dtype: int64

In [15]:
# Find rows where CustomerID is null
null_customer_df = df[df["CustomerID"].isnull()].copy()

# Columns to compare (excluding CustomerID)
compare_cols = [col for col in df.columns if col != "CustomerID"]

# Find rows where CustomerID exists
non_null_customer_df = df[df["CustomerID"].notnull()].copy()

# Merge to identify matching rows
duplicate_like_nulls = null_customer_df.merge(
    non_null_customer_df,
    on=compare_cols,
    how="inner"
)

# Display matching rows
duplicate_like_nulls.head()

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID_x, Country, CustomerID_y]
Index: []

In [16]:
duplicate_like_nulls.shape[0]

0

In [17]:
# Rows where CustomerID is null
# AND Quantity = 0 OR UnitPrice = 0

null_customer_zero_df = df[
    (df["CustomerID"].isnull()) &
    (
        (df["Quantity"] <= 0) |
        (df["UnitPrice"] <= 0)
    )
]

null_customer_zero_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
6391,536941,22734,amazon,20,2010-12-03 12:08:00,0.00,NaN,United Kingdom
6392,536942,22139,amazon,15,2010-12-03 12:08:00,0.00,NaN,United Kingdom
7313,537032,21275,?,-30,2010-12-03 16:50:00,0.00,NaN,United Kingdom
11502,C537251,22429,ENAMEL MEASURING JUG CREAM,-2,2010-12-06 10:45:00,4.25,NaN,United Kingdom
11503,C537251,22620,4 TRADITIONAL SPINNING TOPS,-8,2010-12-06 10:45:00,1.25,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
535336,581213,22576,check,-30,2011-12-07 18:38:00,0.00,NaN,United Kingdom
536908,581226,23090,missing,-338,2011-12-08 09:56:00,0.00,NaN,United Kingdom
538504,581406,46000M,POLYESTER FILLER PAD 45x45cm,240,2011-12-08 13:58:00,0.00,NaN,United Kingdom
538505,581406,46000S,POLYESTER FILLER PAD 40x40cm,300,2011-12-08 13:58:00,0.00,NaN,United Kingdom
538919,581422,23169,smashed,-235,2011-12-08 15:24:00,0.00,NaN,United Kingdom

# Dirty data inspection

**InvoiceNo** have following
a 6-digit integral number uniquely assigned to each transaction. If this code starts with letter 'c', it indicates a cancellation

So if the any entry is less than 6 digit or if it is more than 6 digit and does not have C in starting of it. That data I want to see.

In [5]:
# Convert to string first
df["InvoiceNo"] = df["InvoiceNo"].astype(str)

# Condition for valid InvoiceNo
valid_invoice = (
    df["InvoiceNo"].str.match(r'^\d{6}$') |      # exactly 6 digits
    df["InvoiceNo"].str.match(r'^C\d{6}$')       # C followed by 6 digits
)

# Invalid InvoiceNo rows
invalid_invoice_df = df[~valid_invoice]

invalid_invoice_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299982,A563185,B,Adjust bad debt,1,2011-08-12 14:50:00,11062.06,NaN,United Kingdom
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [6]:
# Convert StockCode to string
df["StockCode"] = df["StockCode"].astype(str)

# Valid StockCode condition
valid_stockcode = df["StockCode"].str.match(r'^\d{5}$')

# Invalid StockCode rows
invalid_stockcode_df = df[~valid_stockcode]

invalid_stockcode_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
45,536370,POST,POSTAGE,3,2010-12-01 08:45:00,18.00,12583.0,France
...,...,...,...,...,...,...,...,...
541778,581578,84997C,CHILDRENS CUTLERY POLKADOT BLUE,8,2011-12-09 12:16:00,4.15,12713.0,Germany
541809,581579,85099C,JUMBO BAG BAROQUE BLACK WHITE,10,2011-12-09 12:19:00,1.79,17581.0,United Kingdom
541838,581580,84993A,75 GREEN PETIT FOUR CASES,2,2011-12-09 12:20:00,0.42,12748.0,United Kingdom
541844,581580,85049A,TRADITIONAL CHRISTMAS RIBBONS,1,2011-12-09 12:20:00,1.25,12748.0,United Kingdom
541853,581580,85049E,SCANDINAVIAN REDS RIBBONS,2,2011-12-09 12:20:00,1.25,12748.0,United Kingdom

In [13]:
df[df["StockCode"] == "84993A"]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
5691,536874,84993A,75 GREEN PETIT FOUR CASES,1,2010-12-03 11:35:00,0.42,16891.0,United Kingdom
18483,537823,84993A,75 GREEN PETIT FOUR CASES,2,2010-12-08 14:25:00,0.84,NaN,United Kingdom
19735,537888,84993A,75 GREEN PETIT FOUR CASES,24,2010-12-09 10:04:00,0.42,15358.0,United Kingdom
25856,538418,84993A,75 GREEN PETIT FOUR CASES,2,2010-12-12 12:00:00,0.42,17372.0,United Kingdom
28729,538655,84993A,75 GREEN PETIT FOUR CASES,6,2010-12-13 15:16:00,0.42,17375.0,United Kingdom
36419,539451,84993A,75 GREEN PETIT FOUR CASES,1,2010-12-17 16:59:00,0.84,NaN,United Kingdom
43291,540026,84993A,75 GREEN PETIT FOUR CASES,1,2011-01-04 13:25:00,0.84,NaN,United Kingdom
43600,540098,84993A,75 GREEN PETIT FOUR CASES,1,2011-01-04 15:50:00,0.42,16241.0,United Kingdom
44044,540154,84993A,75 GREEN PETIT FOUR CASES,1,2011-01-05 11:30:00,0.84,NaN,United Kingdom
48723,540473,84993A,75 GREEN PETIT FOUR CASES,3,2011-01-07 14:31:00,0.42,17284.0,United Kingdom
54571,540957,84993A,75 GREEN PETIT FOUR CASES,2,2011-01-12 13:30:00,0.42,15311.0,United Kingdom
55549,540995,84993A,75 GREEN PETIT FOUR CASES,1,2011-01-13 09:30:00,0.83,NaN,United Kingdom
68600,541870,84993A,75 GREEN PETIT FOUR CASES,1,2011-01-24 09:39:00,0.83,NaN,United Kingdom
74324,542420,84993A,75 GREEN PETIT FOUR CASES,2,2011-01-27 18:05:00,0.42,17180.0,United Kingdom
87063,543631,84993A,75 GREEN PETIT FOUR CASES,2,2011-02-10 16:17:00,0.42,14081.0,United Kingdom
97180,544599,84993A,75 GREEN PETIT FOUR CASES,1,2011-02-21 18:15:00,0.83,NaN,United Kingdom
117902,546412,84993A,75 GREEN PETIT FOUR CASES,2,2011-03-11 16:50:00,0.42,12748.0,United Kingdom
139063,548267,84993A,75 GREEN PETIT FOUR CASES,24,2011-03-30 11:32:00,0.42,16954.0,United Kingdom
143716,548711,84993A,75 GREEN PETIT FOUR CASES,1,2011-04-03 14:24:00,0.42,18116.0,United Kingdom
148176,549185,84993A,75 GREEN PETIT FOUR CASES,24,2011-04-07 09:35:00,0.42,18272.0,United Kingdom
153642,549771,84993A,75 GREEN PETIT FOUR CASES,24,2011-04-12 11:43:00,0.42,14669.0,United Kingdom
161371,550474,84993A,75 GREEN PETIT FOUR CASES,1,2011-04-18 13:58:00,0.83,NaN,United Kingdom
165583,550818,84993A,75 GREEN PETIT FOUR CASES,1,2011-04-20 17:10:00,0.42,15912.0,United Kingdom
168916,551152,84993A,75 GREEN PETIT FOUR CASES,2,2011-04-26 14:47:00,0.42,13230.0,United Kingdom
178652,552234,84993A,75 GREEN PETIT FOUR CASES,1,2011-05-06 16:01:00,0.83,NaN,United Kingdom
187844,553009,84993A,75 GREEN PETIT FOUR CASES,24,2011-05-12 16:52:00,0.42,13601.0,United Kingdom
208796,555149,84993A,75 GREEN PETIT FOUR CASES,1,2011-05-31 15:49:00,0.83,NaN,United Kingdom
231769,557281,84993A,75 GREEN PETIT FOUR CASES,1,2011-06-19 12:23:00,0.42,13632.0,United Kingdom
244992,558565,84993A,75 GREEN PETIT FOUR CASES,2,2011-06-30 13:58:00,0.42,14803.0,United Kingdom
249534,558904,84993A,75 GREEN PETIT FOUR CASES,1,2011-07-04 16:18:00,0.83,NaN,United Kingdom
261862,559893,84993A,75 GREEN PETIT FOUR CASES,2,2011-07-13 12:06:00,0.42,14498.0,United Kingdom
271870,560723,84993A,75 GREEN PETIT FOUR CASES,1,2011-07-20 13:53:00,0.42,16464.0,United Kingdom
294021,562680,84993A,75 GREEN PETIT FOUR CASES,3,2011-08-08 13:46:00,0.42,17954.0,United Kingdom
306735,563840,84993A,75 GREEN PETIT FOUR CASES,24,2011-08-19 13:33:00,0.42,14712.0,United Kingdom
307536,563922,84993A,75 GREEN PETIT FOUR CASES,1,2011-08-21 14:10:00,0.42,14529.0,United Kingdom
354245,567866,84993A,75 GREEN PETIT FOUR CASES,24,2011-09-22 14:13:00,0.42,16669.0,United Kingdom
357118,568066,84993A,75 GREEN PETIT FOUR CASES,2,2011-09-23 13:48:00,0.42,14529.0,United Kingdom
365959,568716,84993A,75 GREEN PETIT FOUR CASES,1,2011-09-28 16:13:00,0.83,NaN,United Kingdom
366194,568719,84993A,75 GREEN PETIT FOUR CASES,1,2011-09-28 16:19:00,0.83,NaN,United Kingdom
368216,568949,84993A,75 GREEN PETIT FOUR CASES,1,2011-09-29 15:13:00,0.83,NaN,United Kingdom
370814,569202,84993A,75 GREEN PETIT FOUR CASES,12,2011-09-30 17:22:00,0.83,NaN,United Kingdom
379742,569700,84993A,75 GREEN PETIT FOUR CASES,1,2011-10-05 15:56:00,0.83,NaN,United Kingdom
388025,570411,84993A,75 GREEN PETIT FOUR CASES,24,2011-10-10 13:11:00,0.42,16954.0,United Kingdom
392431,570690,84993A,75 GREEN PETIT FOUR CASES,1,2011-10-11 16:37:00,0.83,NaN,United Kingdom
396735,571082,84993A,75 GREEN PETIT FOUR CASES,1,2011-10-13 15:25:00,0.83,NaN,United Kingdom
405871,571716,84993A,75 GREEN PETIT FOUR CASES,1,2011-10-18 17:05:00,0.83,NaN,United Kingdom
464500,576099,84993A,75 GREEN PETIT FOUR CASES,24,2011-11-14 10:28:00,0.42,13021.0,United Kingdom
466502,576329,84993A,75 GREEN PETIT FOUR CASES,1,2011-11-14 15:22:00,0.83,NaN,United Kingdom
481700,577358,84993A,75 GREEN PETIT FOUR CASES,5,2011-11-18 15:59:00,0.83,NaN,United Kingdom
487912,577784,84993A,75 GREEN PETIT FOUR CASES,24,2011-11-21 16:24:00,0.42,13862.0,United Kingdom
532065,580983,84993A,75 GREEN PETIT FOUR CASES,1,2011-12-06 16:26:00,0.83,NaN,United Kingdom
533041,581006,84993A,75 GREEN PETIT FOUR CASES,24,2011-12-07 08:45:00,0.42,14911.0,EIRE
538388,581405,84993A,75 GREEN PETIT FOUR CASES,1,2011-12-08 13:50:00,0.42,13521.0,United Kingdom
540130,581467,84993A,75 GREEN PETIT FOUR CASES,1,2011-12-08 19:24:00,0.42,13077.0,United Kingdom
541838,581580,84993A,75 GREEN PETIT FOUR CASES,2,2011-12-09 12:20:00,0.42,12748.0,United Kingdom